FLAGS = -g -Wall -std=c11
FILES = CalendarParser.c LinkedListAPI.c readFile.c BasicFunctions.c

all :
	gcc calMain.c $(FILES) $(FLAGS) -o runCal


UI:
	gcc a2main.c $(FILES) $(FLAGS) -lncurses -o uiTest